import pc from 'picocolors';
import { FLEET_VERSION } from './presets.js';
import { stripAnsi } from './terminal-card.js';

/**
 * Fleet visual design system palette extracted from procedural origin hash:
 * bbf65d904db96f87e74619fc0f7eb9084bab829287cf8b14eda5b727a2c90c9b
 */
export const FLEET_PALETTE = {
  commandNight: '#050811',
  radarChartreuse: '#BBF65D',
  thrusterCobalt: '#4619FC',
  battleshipSlate: '#829287',
  ordnanceFlare: '#CF8B14',
} as const;

/**
 * Fleet high-contrast ASCII emblem.
 */
export const FLEET_ASCII_EMBLEM = [
  '  ███████╗██╗     ███████╗███████╗████████╗',
  '  ██╔════╝██║     ██╔════╝██╔════╝╚══██╔══╝',
  '  █████╗  ██║     █████╗  █████╗     ██║   ',
  '  ██╔══╝  ██║     ██╔══╝  ██╔══╝     ██║   ',
  '  ██║     ███████╗███████╗███████╗   ██║   ',
  '  ╚═╝     ╚══════╝╚══════╝╚══════╝   ╚═╝   ',
];

export interface FleetBannerDetail {
  label: string;
  value: string;
}

export interface FleetBannerOptions {
  command: string;
  subtitle?: string;
  details?: FleetBannerDetail[];
  width?: number;
}

/**
 * Generates the unified Fleet run badge markdown snippet.
 */
export function getFleetRunBadge(
  runId: string = '${GITHUB_RUN_ID:-}',
  serverUrl: string = '${GITHUB_SERVER_URL:-https://github.com}',
  repository: string = '${GITHUB_REPOSITORY:-Jonah-Projects/jonah-fleet}'
): string {
  const runUrl = `${serverUrl}/${repository}/actions/runs/${runId}`;
  return `[![Fleet](https://img.shields.io/badge/Fleet-Autonomous_Command-BBF65D?style=flat&logo=githubactions)](${runUrl})`;
}

/**
 * Generates the unified Fleet session footer markdown snippet.
 */
export function getFleetFooter(
  runId: string = '${GITHUB_RUN_ID:-}',
  serverUrl: string = '${GITHUB_SERVER_URL:-https://github.com}',
  repository: string = '${GITHUB_REPOSITORY:-Jonah-Projects/jonah-fleet}'
): string {
  return `${getFleetRunBadge(runId, serverUrl, repository)}\n\n_Generated by [Antigravity](${serverUrl}/${repository}/actions/runs/${runId})_`;
}

/**
 * Renders the tactical Fleet welcome and command banner.
 */
export function renderFleetBanner(options: FleetBannerOptions): string {
  const width = options.width || Math.min(Math.max((process.stdout.columns || 80) - 4, 60), 80);
  const borderChar = '─';
  const horizontal = borderChar.repeat(Math.max(10, width - 2));

  const border = (s: string) => pc.dim(pc.gray(s));
  const emblemLine = (s: string) => pc.bold(pc.green(s));

  const lines: string[] = [];
  lines.push(border(`┌${horizontal}┐`));

  if (width >= 72) {
    const telemetry = [
      pc.bold(pc.cyan('FLEET // COMMAND')),
      pc.dim(pc.gray('SYS: ')) + pc.green('READY') + pc.dim(pc.gray(' [bbf65d90]')),
      pc.dim(pc.gray('CMD: ')) + pc.bold(pc.white(options.command.toUpperCase())),
      pc.dim(pc.gray('VEC: ')) + pc.green('#BBF65D') + pc.dim(pc.gray(' · ')) + pc.blue('#4619FC'),
      pc.dim(pc.gray('VER: ')) + pc.cyan(`v${FLEET_VERSION}`),
      options.subtitle
        ? pc.dim(pc.gray('OP:  ')) + pc.yellow(options.subtitle.length > 22 ? options.subtitle.slice(0, 19) + '...' : options.subtitle)
        : pc.dim(pc.gray('OP:  ')) + pc.green('ONLINE'),
    ];

    for (let i = 0; i < FLEET_ASCII_EMBLEM.length; i++) {
      const art = FLEET_ASCII_EMBLEM[i];
      const info = telemetry[i] || '';
      const combined = `${art}   ${info}`;
      const plainLen = stripAnsi(combined).length;
      const pad = ' '.repeat(Math.max(1, width - 2 - plainLen));

      lines.push(`${border('│')}${emblemLine(art)}   ${info}${pad}${border('│')}`);
    }
  } else {
    // Compact rendering for narrow viewports
    const header = ` ⚡ FLEET // COMMAND · ${options.command.toUpperCase()}`;
    const headerPlain = stripAnsi(header);
    lines.push(
      `${border('│')}${pc.bold(pc.cyan(header))}${' '.repeat(Math.max(1, width - 2 - headerPlain.length))}${border('│')}`
    );

    const sub = `   SYS: READY · v${FLEET_VERSION}${options.subtitle ? ` · ${options.subtitle}` : ''}`;
    const subPlain = stripAnsi(sub);
    const truncatedSub = subPlain.length > width - 4 ? sub.slice(0, width - 7) + '...' : sub;
    const finalSubPlain = stripAnsi(truncatedSub);
    lines.push(
      `${border('│')}${pc.dim(pc.gray(truncatedSub))}${' '.repeat(Math.max(1, width - 2 - finalSubPlain.length))}${border('│')}`
    );
  }

  if (options.details && options.details.length > 0) {
    lines.push(border(`├${horizontal}┤`));
    for (const detail of options.details) {
      const row = `  • ${pc.dim(pc.gray(detail.label.toUpperCase() + ':'))} ${pc.white(detail.value)}`;
      const rowPlain = stripAnsi(row);
      const truncatedRow =
        rowPlain.length > width - 4
          ? `  • ${pc.dim(pc.gray(detail.label.toUpperCase() + ':'))} ${pc.white(detail.value.slice(0, width - detail.label.length - 12) + '...')}`
          : row;
      const finalPlain = stripAnsi(truncatedRow);
      lines.push(
        `${border('│')}${truncatedRow}${' '.repeat(Math.max(1, width - 2 - finalPlain.length))}${border('│')}`
      );
    }
  }

  lines.push(border(`└${horizontal}┘`));
  return lines.join('\n');
}
